Table of Contents:
1. [`np.array`](#scrollTo=E66I696NTE5z&line=2&uniqifier=1)
    - [Initializing](#scrollTo=edcFkBqeUD-h&line=2&uniqifier=1)
    - [Array Shape](#scrollTo=MQq4cFv1fq6P&line=8&uniqifier=1)
    - [Slicing](#scrollTo=tF1iZy19n0Ur&line=1&uniqifier=1)
2. [`np.ndarray`](#scrollTo=snZeCqZymSFK&line=5&uniqifier=1)

In [2]:
import numpy as np

# Numpy Array
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers indicating the number of dimensions and the number of its elements for each dimensions.

## Initializing
Below are some of the ways to initialize the numpy array

In [56]:
# Make a Numpy array with two dimensions and three elements each, fill it with zero
init_nparray_zero = np.zeros((2, 3))
print(f'Type of array: {type(init_nparray_zero)}')
print(init_nparray_zero, '\n')

# Make a Numpy array with two dimensions and three elements each, fill it with one
init_nparray_ones = np.ones((3, 2))
print(f'Type of array: {type(init_nparray_ones)}')
print(init_nparray_ones, '\n')

# Make a single dimension numpy array
init_nparray_single = np.array([1, 2, 3])
print(f'Type of array: {type(init_nparray_single)}')
print(init_nparray_single, '\n')

# Make a multiple dimensions numpy array
init_nparray_multi = np.array([[1, 2, 3], [4, 5, 6]])
print(f'Type of array: {type(init_nparray_multi)}')
print(init_nparray_multi)

Type of array: <class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]] 

Type of array: <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]] 

Type of array: <class 'numpy.ndarray'>
[1 2 3] 

Type of array: <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


## Shape of Array
Shape of numpy array basically describing the number of dimensions and elements for each of the dimension. 

E.g: (3, 2) mean the array has 3 dimensions and 2 elements for each dimensions.

However, in some cases shape behave unqiuely. Let's say you have a shape of (2,); that shape basically mean a 1 dimensional array with 2 elements inside, 

or if you have a shape of (2, 3, 4); it basically mean 2 dimensionals array, with 3 nested array for each dimension, and 4 elements for each nested array.

In [58]:
np.zeros((2, 3, 4))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [60]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.zeros((2,))

array([0., 0.])

## Slice the array
When you slice the Numpy array, the first argument is the dimension to which you wanted to fetch the elements, it could be a single index number or a range; and then the second argument is the index of the element, again, it could be a single index number or a range.

In [71]:
#initialize the array
sample_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sample_arr[2, 2]

9

In [72]:
sample_arr[:2, :2]

array([[1, 2],
       [4, 5]])

# Numpy NDArray
Numpy array represent a multidimentionals, homogeneous array of fixed sized items. The array should be constructed using `array`, `zeros`, or `empty`.
- `array`: to construct an array
- `zeros`: create an array and fill its elements to zero
- `empty`: create an array, but leave its allocated memory unchanged

## Parameters
`np.ndarray(shape, dtype, buffer, offset, strides, order)`
- `shape`: the shape of created array
- `dtype`: datatype, **optional**. This is to tell Numpy how to interpret the data
- `buffer`: object exposing buffer interface, **optional**. Used to fill array with data
- `offset`: int, **optional**. Offset of array data in buffer.
- `strides`: tuple of ints, **optional**. Stride of data in memory.
- `order`: {'C', 'F'}, **optional**. Row major (C-style) or column major(Fortran-style) order.

In [27]:
list_1 = np.ndarray(shape=(3,), dtype=float, order='F')
list_2 = np.ndarray(shape=(3, 2), dtype=float, order='F')

print(f'list_1: \n{list_1}\n')
print(f'list_2: \n{list_2}')

list_1: 
[4.66870872e-310 4.66860294e-310 4.66870872e-310]

list_2: 
[[4.66870712e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [45]:
np.ndarray((2,), buffer=np.array([1, 9, 3]), offset=np.int_().itemsize, dtype=int)

array([3])

## `ndarray.shape`
`ndarray.shape` define the shape of `ndarray` in form of integer tuple. The shape basically means its dimensions and elements. When you see the shape of, say, (3, 2), it means that the `ndarray` has 3 dimensions with 2 elements each.

## `ndarray` slicing
If you want to slice your `ndarray`, the format a little bit different from normal python array/list.

TypeError: ignored