# Tensors
Tensors are a **specialized data** structure that are **very similar to arrays and matrices**. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s *ndarrays*, except that **tensors can run on GPUs or other hardware accelerators**. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label). Tensors are also optimized for automatic differentiation (we’ll see more about that later in the [Autograd](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label) section). If you’re familiar with *ndarrays*, you’ll be right at home with the Tensor API. If not, follow along!

In [ ]:
import torch
import numpy as np

## Initializing a Tensor
Tensor can be initialized in various ways.

### Directly from the data
Tensors can be created directly from the data. In this case, data `type` will be automatically referred.

In [ ]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print('data variable:', data, '| type:', type(data))
print('x_data variable:', x_data, '| type:', type(x_data))

data variable: [[1, 2], [3, 4]] | type: <class 'list'>
x_data variable: tensor([[1, 2],
        [3, 4]]) | type: <class 'torch.Tensor'>


### From NumPy Array
Tensors can be created from NumPy arrays (and vice versa - see [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)).

In [ ]:
np_array = np.array(data)
x_np = torch.tensor(np_array)

print('np_array variable:', np_array, '| type:', type(np_array))
print('x_np variable:', x_np, '| type:', type(x_np))

np_array variable: [[1 2]
 [3 4]] | type: <class 'numpy.ndarray'>
x_np variable: tensor([[1, 2],
        [3, 4]]) | type: <class 'torch.Tensor'>


### From Another Tensor
The new tensor will **retain** the properties (shapes, datatype) of the argument tensor, unless explicitly overridden. The data, however, will be completely new.

**Notes**: `dtype` is datatype

In [ ]:
# Will retain the properties
x_ones = torch.ones_like(x_data)


# Will be overrides the datatype of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)

print('Ones tensor: \n', x_ones, '\n')
print('Random Tensor: \n', x_rand)

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6158, 0.3911],
        [0.7273, 0.8181]])


### With Random or Constant Value
`shape` is a tuple of tensor dimensions. In the function below, it determines the dimensionality of the output tensor.

In [ ]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape, dtype=torch.int)
zeros_tensor = torch.zeros(shape)

print('Random tensor:\n', rand_tensor)
print('Ones tensor:\n', ones_tensor)
print('Zeros tensor:\n', zeros_tensor)

Random tensor:
 tensor([[0.9356, 0.8515, 0.1594],
        [0.8874, 0.4868, 0.2271]])
Ones tensor:
 tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of Tensor
Tensor attributes describe their shape, datatype, and the device on which they are stored

In [ ]:
tensor = torch.rand(3, 4)
print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Devoce tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Devoce tensor is stored on: cpu


## Operations on Tensor
Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html).

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). **If you’re using Google Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.**

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using `.to` method (after checking for GPU availability). **Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!**

In [ ]:
# Move operations to GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

Try out some of the operations from the list. If you’re familiar with the NumPy API, you’ll find the Tensor API a breeze to use.

### Standart NumPy-like indexing and slicing

In [ ]:
tensor = torch.ones(4, 4)

print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])

tensor[:, 1] = 0
print(tensor)
print(tensor[1, -1])

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor(1.)


### Joining Tensors
You can use `tensor.cat` to concatenate a sequence of tensors along a given dimension. See also [`torch.stack`](https://pytorch.org/docs/stable/generated/torch.stack.html), another tensor joining op that is subtly different from `torch.cat`.

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Arithmetic Operation

In [ ]:
# This computes the matrix multiplications between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
print(f'y1: {y1}')
print(f'y2: {y2}')
print(f'y3: {y3}')
print(f'torch.matmul: {torch.matmul(tensor, tensor.T, out=y3)}\n')

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
print(f'z1: {z1}')
print(f'z2: {z2}')
print(f'z3: {z3}')
print(f'torch.mul: {torch.mul(tensor, tensor, out=z3)}')

y1: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3: tensor([[0.0021, 0.0093, 0.4824, 0.0660],
        [0.3611, 0.8822, 0.4078, 0.9826],
        [0.1399, 0.8871, 0.3738, 0.8707],
        [0.1428, 0.8904, 0.4971, 0.8383]])
torch.matmul: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

z1: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3: tensor([[0.3280, 0.8682, 0.0657, 0.3915],
        [0.0731, 0.6078, 0.5044, 0.9709],
        [0.8445, 0.3832, 0.1441, 0.4772],
        [0.5930, 0.2461, 0.9264, 0.4297]])
torch.mul: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [

### Single-element tensors
If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using `item()`:

In [ ]:
agg = tensor.sum()
agg_item = agg.item()

# Without .item()
print(agg, type(agg))

# With .item()
print(agg_item, type(agg_item))

tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>


### In-place operations
Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

**IMPORTANT NOTE**: *In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.*

In [ ]:
print(f'Before: {tensor}, \n')
tensor.add_(5)
print(f'After: {tensor}')

Before: tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]), 

After: tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


## Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

### Tensor to NumPy Array


In [ ]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array

In [ ]:
t.add_(1)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to tensor

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.

In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
